### ISSUE TITLE
[Bug] dirvish-side re-uses session incorrectly

### ISSUE THREAD

**Issue by jdtsmith** [alexluigit/dirvish#135]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When a dirvish-side session has already been opened and then closed, `dirvish--reuse-session` re-opens it in the initial location.  If you then invoke `dirvish-side` from another buffer without an associated file, like a magit buffer, by the time the `nil` file path is noticed and `default-directory` is used as a backup, the old dirvish-side buffer is already the current buffer, and _it's_ (dired) file-path is incorrectly used.

### Steps to reproduce

1. Open and then close dirvish-side in some buffer without a project. 
2. In a project, open its magit buffer.
3. Invoke dirvish-side from the magit buffer (which has no associated file). 

### Expected behavior

The `default-directory` in a buffer from which dirvish-side is launched is respected. 

### OS

MacOS

### Emacs Version

28

**Comment by alexluigit** [comment]
I'm not able to reproduce it according to your description.

https://user-images.githubusercontent.com/16313743/187254173-f5849b8f-b3b8-4a94-9234-e82d9b0d526d.mp4

BTW are you at the latest commit?

**Comment by jdtsmith** [comment]
Latest commit indeed fixes this behavior; but another error appears when switching back and forth to dirvish-side in a project, and in my .emacs:

```elisp
Debugger entered--Lisp error: (error "No file on this line")
  error("No file on this line")
  dired-move-to-filename(t)
  dired-get-filename()
  dirvish-subtree-expand-to("/Users/jdsmith/.emacs")
  dirvish-subtree-expand-to("/Users/jdsmith/.emacs")
  dirvish-side--new("/Users/jdsmith/")
  dirvish-side(nil)
  funcall-interactively(dirvish-side nil)
  command-execute(dirvish-side)
```

**Comment by alexluigit** [comment]
Is ~/.emacs hidden or nonexist? [82c7741](https://github.com/alexluigit/dirvish/commit/82c7741eec586e56af5c98f7c0b7eaba73cecfa1) should fixed it if that's the case.

**Comment by jdtsmith** [comment]
In the latest I'm now getting the following redisplay error:

```elisp
Debugger entered--Lisp error: (wrong-type-argument dirvish nil)
  signal(wrong-type-argument (dirvish nil))
  (or (progn (and (memq (type-of dv) cl-struct-dirvish-tags) t)) (signal 'wrong-type-argument (list 'dirvish dv)))
  (progn (or (progn (and (memq (type-of dv) cl-struct-dirvish-tags) t)) (signal 'wrong-type-argument (list 'dirvish dv))) (let* ((v dv)) (aset v 11 (get-buffer-window (cdr (progn (or (progn ...) (signal ... ...)) (aref dv 19)))))))
  (let ((dv (dirvish-curr))) (if (and (not (active-minibuffer-window)) (let* ((pair (assq :minimized dirvish--props)) (val (cdr pair))) val)) (progn (dirvish--build dv))) (progn (or (progn (and (memq (type-of dv) cl-struct-dirvish-tags) t)) (signal 'wrong-type-argument (list 'dirvish dv))) (let* ((v dv)) (aset v 11 (get-buffer-window (cdr (progn (or ... ...) (aref dv 19))))))))
  dirvish-winconf-change-h()
  redisplay_internal\ \(C\ function\)()
```

**Comment by alexluigit** [comment]
I can't reproduce this. `emacs -q`? 

```emacs-lisp
(defun dirvish-winconf-change-h ()
 ""
  ;; Will change this to `when-let` fix the issue?
  (let ((dv (dirvish-curr)))
```

**Comment by alexluigit** [comment]
Let me know if 8ce8145 fixed this.
 
> Is there somewhere I can look to find the session initialization?

Session initialization only occurs when the minibuffer command calls `find-directory-functions` where `dired-noselect` is replaced by `dirvish--noselect`.  So `find-file` (C-x C-f) / `consult-bookmark` creates a new session, while `consult-buffer` does not.  The error 

> It's possible consult's preview disables the hooks dired/dirvish uses to setup the session state. 

As of now, the session is restored **after** the minibuffer exits on `dirvish-minibuffer-exit-h`.

**Comment by jdtsmith** [comment]
Sadly same behavior: if I _first_ load a dirvish dir, then using consult-buffer to preview + create a new one, all is well.  If I skip the session "warm up" step, `(dirvish-curr)` is `nil` and the same errors commence.

**Comment by alexluigit** [comment]
> BTW, I also notice dirvish-override-dired-mode is called 4 times

Fixed.

>  if I first load a dirvish dir, then using consult-buffer to preview + create a new one, all is well. If I skip the session "warm up" step, (dirvish-curr) is nil and the same errors appear.

I don't understand this part, how do you create a new dired/dirvish buffer using consult-buffer when there are no dired buffers in your buffer list? 

> I note that dirvish-minibuffer-exit-h does not get called when the error occurs. But when the session is warmed up, it does get called.

Do you have any lazy loading setup to delay the `dirvish-override-dired-mode`?

**Comment by jdtsmith** [comment]
> I don't understand this part, how do you create a new dired/dirvish buffer using consult-buffer when there are no dired buffers in your buffer list?

I just use find-file on a directory to open a dirvish session, prior to invoking consult-buffer.  After this, everything works as expected. 

> Do you have any lazy loading setup to delay the dirvish-override-dired-mode?

I tried setting `:defer nil` in my use-package.  And I check to see that `dirvish-override-dired-mode=t` on startup.  But still an initial consult-buffer manages leads to an inoperative dirvish window.  It's missing the header, line highlighting doesn't work, and the nil errors described above happen. 

It's possible this could be blamed on consult-buffer, BTW.  I know it disables a number of hooks during buffer preview (see `consult-preview-allowed-hooks`); perhaps that's triggering the broken session state.

**Comment by alexluigit** [comment]
> But still an initial consult-buffer manages leads to an inoperative dirvish window

I'm not sure I understand you correctly. If you mean:
- `find-file` / `dirvish`  then `consult-buffer`  (works)
-  M-x consult-buffer directly (raise redisplay error and result in a broken dirvish )

Then my question is:  if you didn't do the "warm-up" (namely you didn't have _any dirvish buffer_  in your buffer list), how did you manage to switch to a dirvish buffer ("an inoperative window" as you described) using consult-buffer command? 

> It's possible this could be blamed on consult-buffer, BTW. I know it disables a number of hooks during buffer preview (see `consult-preview-allowed-hooks`); perhaps that's triggering the broken session state. I will say this seems to be new behavior with more recent versions of dirvish; it was all working fine until several days ago.

Perhaps. But I'm not able to reproduce the error with different sets of config I can think of.  Consult works completely fine on my end.

**Comment by jdtsmith** [comment]
> Then my question is: if you didn't do the "warm-up" (namely you didn't have any dirvish buffer in your buffer list), how did you manage to switch to a dirvish buffer ("an inoperative window" as you described) using consult-buffer command?

Sorry I wasn't clear on this.  I'm re-using the dirvish buffer an initial consult-buffer opens (via its preview), by calling consult-buffer _again_ once a project is selected in the "action".  The actual consult-buffer call is from my own [consult-jump-project](https://github.com/jdtsmith/consult-jump-project).

**Comment by jdtsmith** [comment]
Unfortunately despite finding some dired-related issues on reusing the previewed buffer, it seems the issue still lies with dirvish.  Since this showed up somewhat recently, I bisected the last two weeks of commits, and localized the appearance of the issue to dfcc485.

**Comment by alexluigit** [comment]
When I invoke consult-buffer, I got these sources: 
- Buffer (no dirvish buffer inside, since I didn't created any) 
- File (no dirvish buffer inside because all entries are files rather than directories)
- Bookmark (no preview is showed up for these entries)

So I'm not able to create any dirvish buffers through the preview machinery in consult (let alone switching to them in later commands). In other words, from my limited tests, I don't see any chance that consult-buffer (nor consult-jump-project) would _create_ a dirvish buffer.  If I can replicate the exact scenario you encountered, perhaps I can reproduce the error you mentioned.

**Comment by jdtsmith** [comment]
Thanks, glad you could reproduce.  `consult-jump-project` prompts with a list of Directories (ala projects from `project-known-project-roots`).  Then `consult-buffer` happily provides a dired(=dirvish) preview of each directory as you navigate.  But for efficiency consult delays/defers many of the mode hooks in its preview buffers.  For whatever reason, this confuses the session initialization for dirvish.  I think prior to dfcc485, the frame-parameter was (mostly) protecting against this, but possibly as an unintended side-effect.  

As @minad pointed out, you encounter the same issue if using embark to visit a dired buffer from among the previewed directory candidates, so this isn't specific to `consult-jump-project`.

**Comment by minad** [comment]
> As @minad pointed out, you encounter the same issue if using embark to visit a dired buffer from among the previewed directory candidates, so this isn't specific to consult-jump-project.

But to be clear - before my recent Consult fixes this didn't even work correctly for Dired+Consult+Embark alone. Now it does, so Dirvish must be doing something special with regards of reusing Dirvish buffers.

**Comment by jdtsmith** [comment]
Great work @alexluigit.  All issues with consult-buffer re-use of previewed dirvish buffers are now gone.  And this looks like a nice reduction in the number of advices needed.  Dirvish is improving at an incredible rate!  I am especially enjoying the "wide+narrow" file tree view, starting at the project level and opening the appropriate nested subdirs to reveal the current file in dirvish-side, which I've bound to F9 for easy toggle access.
